spring:
  datasource:
    url: jdbc:mysql://yb.upc.edu.cn:3306/test
    username: liliangbin_test
    password: liliangbin_test
    test-while-idle: true
    validation-query: SELECT 1
  thymeleaf:
    mode: LEGACYHTML5
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
server:
  port: 8081